import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import zhCNIntl from "antd/lib/locale/zh_CN";
import ReduxProvider from "@/redux/provider";
import { MembershipModal } from "@/components/membership/MembershipModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh">
      <body>
        <ReduxProvider>
          <AntdRegistry>
            <ConfigProvider locale={zhCNIntl}>
              {children}
              <MembershipModal />
            </ConfigProvider>
          </AntdRegistry>
        </ReduxProvider>
      </body>
    </html>
  );
}
